# 图数据库类型
graphType: janusgraph
# 图名称
graphName: Graph500
# 默认样本文件
sample: sample/Graph500-kn-sample.txt
samples:
  sp: sample/Graph500-sp-sample.txt
# 超时时间,单位：s
timeout: 3600
# 超时跳过测试项
timeoutStop: false
# 遇到错误时跳过测试项
errorStop: false
# 数据库所在包名
dataBaseClass: com.galaxybase.benchmark.janus.database.Janus
# 自定义参数
parameters:
  propertyFile: janusgraph-Graph500.properties
test:
  - testClass: com.galaxybase.benchmark.janus.function.KNeighbor1
    count: 100
    loop: 1
    timeout: 180
  - testClass: com.galaxybase.benchmark.janus.function.KNeighbor2
    count: 100
    loop: 1
    timeout: 180
  - testClass: com.galaxybase.benchmark.janus.function.KNeighbor3
    count: 10
    loop: 1
  - testClass: com.galaxybase.benchmark.janus.function.KNeighbor4
    count: 10
    loop: 1
  - testClass: com.galaxybase.benchmark.janus.function.KNeighbor5
    count: 10
    loop: 1
  - testClass: com.galaxybase.benchmark.janus.function.KNeighbor6
    count: 10
    loop: 1
  - testClass: com.galaxybase.benchmark.janus.function.ShortestPath
    count: 100
    loop: 1
    sample: sp
    timeout: 300
